backend:
  name: git-gateway
  branch: main # replace with your branch name

media_folder: "assets/uploads" # temporary folder for uploaded files
public_folder: "/assets/uploads"

collections:
  - name: "videos"
    label: "Videos"
    folder: "assets/videos" # where video info will be stored
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Video File", name: "file", widget: "file"}
      - {label: "Month", name: "month", widget: "number"}
      - {label: "Year", name: "year", widget: "number"}
