// videos.js
// Example: fetch all video files saved as JSON/Markdown
// For simplicity, you can convert Markdown/JSON to a single JSON file
// or use a static JSON like `videos.json` generated by CMS

fetch('assets/videos/videos.json') // CMS-generated JSON
  .then(res => res.json())
  .then(data => {
    const videosGrid = document.getElementById('videosGrid');
    videosGrid.innerHTML = '';
    data.forEach(video => {
      const card = document.createElement('div');
      card.classList.add('video-card');
      card.innerHTML = `
        <video controls>
          <source src="${video.file}" type="video/mp4">
        </video>
        <h3>${video.title}</h3>
        <p>${video.description}</p>
      `;
      videosGrid.appendChild(card);
    });
  });
  
// videos-admin.html
const password = prompt("Enter admin password:");
if(password !== "YourSecretPassword"){
  alert("Access Denied");
  window.location.href = "videos.html";
}
